# Generated by Django 5.1.4 on 2025-01-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='phone',
        ),
    ]
